package com.example.backgroundFunction;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path="/demo") //URL starts with /demo after Application path
public class MainController {
    @Autowired //Get the bean called userRepository which is auto-generated by Spring
    private UserRepository userRepository;

    @PostMapping(path="/add") //Map only POST requests
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email) {        //@ResponseBody means the returned String is a response and not a view name
        //@RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        //Returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
